In [5]:
import pandas as pd

data_path = '../data/skin-cancer-mnist-ham10000/'

In [6]:
pd_meta = pd.read_csv(data_path + 'HAM10000_metadata.csv')

In [8]:
set(pd_meta.dx_type)

{'confocal', 'consensus', 'follow_up', 'histo'}

According to data description, only the 'follow-up' category is confirmed and therefore can be used as positive label

In [11]:
sum(pd_meta.dx_type == 'follow_up')

3704

In [18]:
set(pd_meta.dx)

{'akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc'}

According to the data description, the above categories correpond to the following diagnoses:
- Actinic keratoses and intraepithelial carcinoma / Bowen's disease (akiec)
- basal cell carcinoma (bcc)
- benign keratosis-like lesions (solar lentigines / seborrheic keratoses and lichen-planus like keratoses, bkl)
- dermatofibroma (df)
- melanoma (mel)
- melanocytic nevi (nv) 
- vascular lesions (angiomas, angiokeratomas, pyogenic granulomas and hemorrhage, vasc)

In [20]:
pd_meta.head()

lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

we have about 3.7k positive labels

In [12]:
rgb_28 = pd.read_csv(data_path+'hmnist_28_28_RGB.csv')

In [19]:
rgb_28.label

0        2
1        2
2        2
3        2
4        2
5        2
6        2
7        2
8        2
9        2
10       2
11       2
12       2
13       2
14       2
15       2
16       2
17       2
18       2
19       2
20       2
21       2
22       2
23       2
24       2
25       2
26       2
27       2
28       2
29       2
        ..
9985     0
9986     0
9987     0
9988     0
9989     0
9990     0
9991     0
9992     0
9993     0
9994     0
9995     0
9996     0
9997     0
9998     0
9999     0
10000    0
10001    0
10002    0
10003    0
10004    0
10005    0
10006    0
10007    0
10008    0
10009    0
10010    0
10011    0
10012    0
10013    0
10014    6
Name: label, Length: 10015, dtype: int64

Testing out stuff

In [7]:
import numpy as np
import torch

In [10]:
one_hot = np.zeros((1, 5), dtype = np.float32)

In [11]:
one_hot[0][3] = 1

In [12]:
one_hot = torch.from_numpy(one_hot)

In [13]:
one_hot

tensor([[0., 0., 0., 1., 0.]])

In [30]:
pseudo_output = np.array([[1,2,3], [2,3,4], [2,3,4], [3,4,5], [4,5,6]])

In [31]:
pseudo_output = torch.from_numpy(pseudo_output).float().t()

In [32]:
pseudo_output

tensor([[1., 2., 2., 3., 4.],
        [2., 3., 3., 4., 5.],
        [3., 4., 4., 5., 6.]])

In [33]:
pseudo_output.shape

torch.Size([3, 5])

In [34]:
one_hot*pseudo_output

tensor([[0., 0., 0., 3., 0.],
        [0., 0., 0., 4., 0.],
        [0., 0., 0., 5., 0.]])

In [36]:
torch.mm(one_hot, pseudo_output.t())

tensor([[3., 4., 5.]])