In [1]:
import pandas as pd


data_path = '../data/res_model/'

In [6]:
pd_meta = pd.read_csv(data_path + 'HAM10000_metadata.csv')

In [8]:
set(pd_meta.dx_type)

{'confocal', 'consensus', 'follow_up', 'histo'}

According to data description, only the 'follow-up' category is confirmed and therefore can be used as positive label

In [11]:
sum(pd_meta.dx_type == 'follow_up')

3704

In [18]:
set(pd_meta.dx)

{'akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc'}

According to the data description, the above categories correpond to the following diagnoses:
- Actinic keratoses and intraepithelial carcinoma / Bowen's disease (akiec)
- basal cell carcinoma (bcc)
- benign keratosis-like lesions (solar lentigines / seborrheic keratoses and lichen-planus like keratoses, bkl)
- dermatofibroma (df)
- melanoma (mel)
- melanocytic nevi (nv) 
- vascular lesions (angiomas, angiokeratomas, pyogenic granulomas and hemorrhage, vasc)

In [20]:
pd_meta.head()

lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

we have about 3.7k positive labels

In [12]:
rgb_28 = pd.read_csv(data_path+'hmnist_28_28_RGB.csv')

In [19]:
rgb_28.label

0        2
1        2
2        2
3        2
4        2
5        2
6        2
7        2
8        2
9        2
10       2
11       2
12       2
13       2
14       2
15       2
16       2
17       2
18       2
19       2
20       2
21       2
22       2
23       2
24       2
25       2
26       2
27       2
28       2
29       2
        ..
9985     0
9986     0
9987     0
9988     0
9989     0
9990     0
9991     0
9992     0
9993     0
9994     0
9995     0
9996     0
9997     0
9998     0
9999     0
10000    0
10001    0
10002    0
10003    0
10004    0
10005    0
10006    0
10007    0
10008    0
10009    0
10010    0
10011    0
10012    0
10013    0
10014    6
Name: label, Length: 10015, dtype: int64

Testing out stuff

In [3]:
import numpy as np
import torch

In [209]:
one_hot = np.zeros((1, 5), dtype = np.float32)

In [210]:
one_hot[0][3] = 1

In [211]:
one_hot = torch.from_numpy(one_hot)

In [212]:
one_hot

tensor([[0., 0., 0., 1., 0.]])

In [213]:
pseudo_output = np.array([[1,2,3], [2,3,4], [2,3,4], [3,4,5], [4,5,6]])

In [214]:
pseudo_output = torch.from_numpy(pseudo_output).float().t()

In [215]:
pseudo_output

tensor([[1., 2., 2., 3., 4.],
        [2., 3., 3., 4., 5.],
        [3., 4., 4., 5., 6.]])

In [216]:
pseudo_output.shape

torch.Size([3, 5])

In [219]:
torch.sum(one_hot*pseudo_output)

tensor(12.)

In [218]:
torch.mm(one_hot, pseudo_output.t())

tensor([[3., 4., 5.]])

In [4]:
from torchvision import models

In [5]:
model_vgg16 = models.vgg16(pretrained = True)
model_vgg19 = models.vgg19(pretrained = True)

model_vgg16.eval()
model_vgg19.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace)
    (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (17): ReLU(inplace)

In [5]:
model_vgg16.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (17): Conv2d

In [95]:
for name, module in model_vgg.features._modules.items():
    print(name, module)

0 Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
1 ReLU(inplace)
2 Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
3 ReLU(inplace)
4 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
5 Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
6 ReLU(inplace)
7 Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
8 ReLU(inplace)
9 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
10 Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
11 ReLU(inplace)
12 Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
13 ReLU(inplace)
14 Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
15 ReLU(inplace)
16 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
17 Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
18 ReLU(inplace)
19 Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
20 ReLU

In [72]:
xx = torch.randn(1,1)
xx.requires_grad = True

In [73]:
xx

tensor([[-0.6389]], requires_grad=True)

In [74]:
yy = 4 * xx

In [75]:
zz = yy**2

In [76]:
yy_grad = []
def return_grad(grad):
    yy_grad.append(grad)
yy.register_hook(return_grad)

In [77]:
zz.backward()

In [78]:
xx.grad

tensor([[-20.4462]])

In [80]:
yy_grad

[tensor([[-5.1116]])]

In [1]:
import torch
from torch.autograd import Variable
from torch.autograd import Function
from torchvision import models
from torchvision import utils
import cv2
import sys
import numpy as np
import argparse

In [2]:
from torch.autograd import Function

In [4]:
def preprocess_image(img):
	means=[0.485, 0.456, 0.406]
	stds=[0.229, 0.224, 0.225]

	preprocessed_img = img.copy()[: , :, ::-1]
	for i in range(3):
		preprocessed_img[:, :, i] = preprocessed_img[:, :, i] - means[i]
		preprocessed_img[:, :, i] = preprocessed_img[:, :, i] / stds[i]
	preprocessed_img = \
		np.ascontiguousarray(np.transpose(preprocessed_img, (2, 0, 1)))
	preprocessed_img = torch.from_numpy(preprocessed_img)
	preprocessed_img.unsqueeze_(0)
	#input = Variable(preprocessed_img, requires_grad = True)
	input = preprocessed_img
	input.requires_grad = True
	return(input)

In [74]:
class ExtractFeatures:
	"""
	Class for mannually passing the input image through the model
	the gradient at the identified layer will be registered and saved
	"""
	def __init__(self, model, target_layer):
		self.model = model
		self.target_layer = target_layer
		self.gradients = []

	def save_grad(self, grad):
		self.gradients.append(grad)

	def record_and_feed_forward(self, inp):
		# we want to reset the gradient every time we call the method
		self.gradients = []
		layer_output = None
		print(self.model.features)
		for name, layer in self.model.features._modules.items():
			# here we mannually pass the input through the NN until the identified layer
			inp = layer(inp)
			print(name)
			if name[0] == self.target_layer:
				print('yes')
				# here by registering the hook, we tag the layer and notify torch that we want to keep the gradient for this layer
				inp.register_hook(self.save_grad)
				# record the output at the identified layer, the output is the same as the input for the next layer (activation: final ReLU for VGG before classif)
				layer_output = inp
		# need to flatten before the fully connected layers in the classifier half
		inp = inp.view(inp.size(0), -1)
		# classify
		inp = self.model.classifier(inp)
		return(layer_output, inp)

In [35]:
from vgg_pretrained import vgg_preloaded, MelaData, train, train_val_test_split, test_model
import pickle
import torch
from class_activation_map import ExtractFeatures, GradCam

save_dir = '/home/paperspace/projects/skin_cancer/data/res_model/'
model_name = 'test_model_100_loss_0_1995_acc_0_9248.pt'
name = save_dir + model_name

In [27]:
model = vgg_preloaded(7, use_cuda = True)
model.load_state_dict(torch.load(name))
model.model.requires_grad = True

In [82]:
for name, mod in model.model.features._modules.items():
    print(name == target_layers)

False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
False
True
False


In [79]:
target_layers = '29'
feature_extractor = ExtractFeatures(model.model, target_layers)

In [39]:
image_path = '/home/paperspace/projects/skin_cancer/data/skin-cancer-mnist-ham10000/HAM10000_images_part_1/ISIC_0025713.jpg'
img = cv2.imread(image_path, 1)
img = np.float32(cv2.resize(img, (224, 224))) / 255

In [40]:
inp = preprocess_image(img)

In [41]:
inp.shape

torch.Size([1, 3, 224, 224])

In [42]:
inp = inp.cuda()

In [43]:
model = model.cuda()

In [76]:
act, output = feature_extractor.record_and_feed_forward(inp)

Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU(inplace)
  (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): ReLU(inplace)
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (6): ReLU(inplace)
  (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): ReLU(inplace)
  (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): ReLU(inplace)
  (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (13): ReLU(inplace)
  (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (15): ReLU(inplace)
  (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (17): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(

In [77]:
act

In [151]:
model_vgg16.features

Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU(inplace)
  (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): ReLU(inplace)
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (6): ReLU(inplace)
  (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): ReLU(inplace)
  (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): ReLU(inplace)
  (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (13): ReLU(inplace)
  (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (15): ReLU(inplace)
  (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (17): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(

In [152]:
model_vgg19.features

Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU(inplace)
  (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): ReLU(inplace)
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (6): ReLU(inplace)
  (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): ReLU(inplace)
  (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): ReLU(inplace)
  (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (13): ReLU(inplace)
  (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (15): ReLU(inplace)
  (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (17): ReLU(inplace)
  (18): MaxPool2d(kernel_size=2, stride=2, padding=0, 

In [201]:
output.size()

torch.Size([1, 512, 7, 7])

In [203]:
output.view(output.size(0),-1).size()

torch.Size([1, 25088])

In [206]:
a = 1

In [207]:
print('hi') if a is None else print('lol')

lol


In [229]:
act[-1].cpu().data.numpy()[0].shape

(512, 14, 14)

In [230]:
act[-1].cpu().data.numpy()[0, :].shape

(512, 14, 14)

In [82]:
img = inp

In [83]:
extractfeatures = ExtractFeatures(model_vgg16, '29')

In [84]:
feature, output = extractfeatures.record_and_feed_forward(img)

In [85]:
class_code = np.argmax(output.cpu().data.numpy())

In [86]:
one_hot = np.zeros((1, output.size()[-1]), dtype = np.float32)
one_hot[0][class_code] = 1
one_hot = torch.from_numpy(one_hot)
one_hot.requires_grad = True
one_hot = one_hot.cuda()

In [87]:
activation_value = torch.sum(torch.mm(one_hot, output.t()))

In [88]:
output[0].shape

torch.Size([1000])

In [89]:
activation_value = output[0][class_code]

In [90]:
activation_value

tensor(15.6454, device='cuda:0', grad_fn=<SelectBackward>)

In [91]:
model_vgg16.features.zero_grad()
model_vgg16.classifier.zero_grad()

In [92]:
activation_value.backward()

In [93]:
grads = extractfeatures.gradients[-1].cpu().data.numpy()

In [94]:
grads.shape

(1, 512, 14, 14)

In [95]:
grads = np.mean(grads, axis = (2,3))[0]

In [96]:
target_layer = feature.cpu().data.numpy()[0] # in case the input target_layer is multiple

In [115]:
cam = np.zeros(target_layer.shape[1 : ], dtype = np.float32)

In [116]:
for i, w in enumerate(grads):
    cam += w * target_layer[i, :, :]
cam = np.maximum(cam, 0)
cam = cv2.resize(cam, (600, 450))
cam = cam - np.min(cam)
cam = cam / np.max(cam)

In [10]:
image_path = '/home/paperspace/projects/skin_cancer/data/skin-cancer-mnist-ham10000/HAM10000_images_part_1/ISIC_0025713.jpg'
img = cv2.imread(image_path, 1)
img = np.float32(cv2.resize(img, (224, 224))) / 255
#img = np.float32(img) / 255

In [118]:
img.shape

(450, 600, 3)

In [119]:
heatmap = cv2.applyColorMap(np.uint8(255*cam), cv2.COLORMAP_JET)
heatmap = np.float32(heatmap) / 255
cam_ = heatmap + np.float32(img)
cam_ = cam_ / np.max(cam_)

In [ ]:
cv2.imshow('img', cam_)

In [120]:
cv2.imwrite("cam.jpg", np.uint8(255 * cam_))

True

In [103]:
np.uint8(255*cam)

array([[189, 189, 189, ...,  89,  89,  89],
       [189, 189, 189, ...,  89,  89,  89],
       [189, 189, 189, ...,  89,  89,  89],
       ..., 
       [226, 226, 226, ..., 255, 255, 255],
       [226, 226, 226, ..., 255, 255, 255],
       [226, 226, 226, ..., 255, 255, 255]], dtype=uint8)

In [1]:
from vgg_pretrained import vgg_preloaded, MelaData, train, train_val_test_split, test_model

In [1]:
from vgg_transfer_learning_version import vgg_preloaded, MelaData, train

IndentationError: unindent does not match any outer indentation level (vgg_transfer_learning_version.py, line 141)

In [2]:
import os
import torch
import pandas as pd
from skimage import io, transform
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
from torchvision import models, transforms, utils
from PIL import Image
from tqdm import tqdm
from torch.optim import Adam
import pickle
import math

In [3]:
data_d = '/home/paperspace/projects/skin_cancer/data/skin-cancer-mnist-ham10000/HAM10000_images_part_1/'
label_dir = '/home/paperspace/projects/skin_cancer/data/skin-cancer-mnist-ham10000/HAM10000_metadata.csv'
save_dir = '/home/paperspace/projects/skin_cancer/data/res_model/'
epoch = 5
mb = 24
num_class = 7
num_workers = 1
cuda = True
conti = False
save = True
name = 'test_model'
lr = 1e-4

In [4]:
res = train(data_dir = data_d, label_dir = label_dir, save_dir = save_dir, epoch = epoch, mb = mb, num_class = num_class, num_workers = num_workers, use_cuda = cuda, conti = conti, lr = lr, save = True)

[Epoch 2]:   0%|          | 0/293 [00:00<?, ?it/s]

Train - Loss: 0.8592 Acc: 0.6926


[Epoch 3]:   0%|          | 0/293 [00:00<?, ?it/s]

Train - Loss: 0.7120 Acc: 0.7476


[Epoch 4]:   0%|          | 0/293 [00:00<?, ?it/s]

Train - Loss: 0.6427 Acc: 0.7649


[Epoch 5]:   0%|          | 0/293 [00:00<?, ?it/s]

Train - Loss: 0.6117 Acc: 0.7817


[Epoch 5]: 100%|██████████| 293/293 [02:36<00:00,  1.88it/s]


Train - Loss: 0.5698 Acc: 0.7983


In [5]:
val_data = res[2]

In [9]:
def train_val_test_split(dataset, train_split, val_split, test_split):
	"""
	Split data set into training, validation, and test sets.
	"""
	#if train_split + val_split + test_split != 1:
		#print('Incorrect split sizes')

	# Size of data set
	N = dataset.__len__()

	# Size of train set
	train_size = math.floor(train_split * N)

	# Size of validation set
	val_size = math.floor(val_split * N)

	# List of all data indices
	indices = list(range(N))

	# Random selection of indices for train set
	train_ids = np.random.choice(indices, size=train_size, replace=False)
	train_ids = list(train_ids)

	# Deletion of indices used for train set
	indices = list(set(indices) - set(train_ids))

	# Random selection of indices for validation set
	val_ids = np.random.choice(indices, size=val_size, replace=False)
	val_ids = list(val_ids)

	# Selecting remaining indices for test set
	test_ids = list(set(indices) - set(val_ids))

	# Creating subsets
	train_data = torch.utils.data.Subset(dataset, train_ids)
	val_data = torch.utils.data.Subset(dataset, val_ids)
	test_data = torch.utils.data.Subset(dataset, test_ids)
	return(train_data, val_data, test_data)

In [5]:
def train(data_dir, label_dir, save_dir, epoch, mb, num_class, num_workers = 1, use_cuda = False, conti = False, lr = 1e-3, save = True, name = None, train_prop = 0.7):
	# instantiate the vgg model
	model = vgg_preloaded(num_class, use_cuda)

	if name is None:
		name = 'model'

	# if dir does not exit, make it:
	if not os.path.isdir(save_dir):
		os.mkdir(save_dir)

	# define model path
	modelpath = os.path.join(save_dir, '{}.pt'.format(name))

	# do we wanna continue to train
	if os.path.isfile(modelpath) and conti:
		model.load_state_dict(torch.load(modelpath))
	if use_cuda:
		model = model.cuda()
	model.train()

	loss_train = np.zeros(epoch)
	acc_train = np.zeros(epoch)
	loss_fun = torch.nn.CrossEntropyLoss(reduction = 'sum')
	optim = Adam(model.parameters(), lr = lr)
	dataset = MelaData(data_dir = data_dir, label_csv = label_dir)
	val_prop = 1 - train_prop
	train_data, val_data, test_data = train_val_test_split(dataset, train_prop, val_prop, 0.0)

	for epoch_num in range(1, epoch+1):
		running_loss = 0.0
		running_corrects = 0.0
		size = 0

		dataloader = DataLoader(train_data, batch_size = mb, shuffle = True, num_workers = num_workers)

		pbar = tqdm(dataloader)
		pbar.set_description("[Epoch {}]".format(epoch_num))
		for inputs, labels in pbar:
			bs = labels.size(0)
			if use_cuda:
				inputs = inputs.cuda()
				labels = labels.cuda()
			output = model(inputs)
			_, preds = torch.max(output.data, 1)
			loss = loss_fun(output, labels)
			running_loss += loss
			running_corrects += preds.eq(labels.view_as(preds)).sum()
			optim.zero_grad()
			loss.backward()
			optim.step()
			size += bs

		epoch_loss = running_loss / size
		epoch_acc = running_corrects.item() / size
		loss_train[epoch_num-1] = epoch_loss
		acc_train[epoch_num-1] = epoch_acc
		print('Train - Loss: {:.4F} Acc: {:.4f}'.format(epoch_loss, epoch_acc))

	if save:
		torch.save(model.state_dict(), os.path.join(save_dir, '{}.pt'.format(name)))
		torch.save(optim.state_dict(), os.path.join(save_dir, '{}.optim.pt'.format(name)))
	return(loss_train, acc_train, val_data)

In [12]:
loss_train, acc_train, val_data = train(data_dir = data_d, label_dir = label_dir, save_dir = save_dir, epoch = epoch, mb = mb, num_class = num_class, num_workers = num_workers, use_cuda = cuda, conti = conti, lr = lr, save = True)

ValueError: Invalid file path or buffer object type: <class 'NoneType'>

In [7]:
model

vgg_preloaded(
  (model): VGG(
    (features): Sequential(
      (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): ReLU(inplace)
      (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (3): ReLU(inplace)
      (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (6): ReLU(inplace)
      (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (8): ReLU(inplace)
      (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
      (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (11): ReLU(inplace)
      (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (13): ReLU(inplace)
      (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (15): ReLU(inplace)
      (16): MaxPool2d(kernel_size=2, stri

In [6]:
def test_model(model_dir, val_data, label_dir, batch_size, num_workers = 1, use_cuda = False):
    model = vgg_preloaded(7, use_cuda=use_cuda)
    model.load_state_dict(torch.load(model_dir))
    model = model.cuda() if use_cuda else model

    #dataset = MelaData(data_dir = data_dir, label_csv = label_dir)
    dataloader = DataLoader(val_data, batch_size = batch_size, shuffle = False, num_workers = num_workers)
    loss_fn = torch.nn.CrossEntropyLoss(reduction = 'sum')

    model.eval()
    predictions = [] #Store predictions in here
    class_list = [] #store ground truth here

    running_loss = 0.0
    running_corrects = 0
    count = 0
    
    pbar = tqdm(dataloader)
    pbar.set_description("[Epoch {}]".format('Validation'))
    for inputs,classes in pbar:
        if use_cuda:
            inputs = inputs.cuda()
            classes = classes.cuda()
        else:
            inputs = inputs
            classes = classes
        outputs = model(inputs)
        loss = loss_fn(outputs,classes) 
        _,preds = torch.max(outputs.data, 1)
        running_loss += loss.cpu().data.item()
        running_corrects += preds.eq(classes.view_as(preds)).sum()
        predictions += list(preds.cpu().data.numpy())
        if use_cuda:
            class_save = classes.cpu().data.numpy()
        else:
            class_save = classes.data.numpy()
        class_list.append(class_save)
        count +=1

    print('Loss: {:.4f} Acc: {:.4f}'.format(running_loss / len(val_data), running_corrects.data.item() / len(val_data)))
    return({'loss': running_loss / len(val_data), 'acc': running_corrects.data.item() / len(val_data), 'predictions': predictions, 'classes': class_list})

In [7]:
import sys
model_dir = '/home/paperspace/projects/skin_cancer/data/res_model/model.pt'
val_data = val_data
label_dir = None
batch_size = 1
use_cuda = True




res = test_model(model_dir = model_dir, val_data = val_data, label_dir = label_dir, batch_size = 12, use_cuda = use_cuda)

[Epoch Validation]: 100%|██████████| 251/251 [01:01<00:00,  4.10it/s]

Loss: 0.6949 Acc: 0.7636


In [7]:
res.keys()

dict_keys(['loss', 'acc', 'predictions', 'classes'])

In [8]:
from collections import Counter
Counter(res['predictions'])

Counter({0: 2544, 1: 35, 2: 149, 3: 5, 4: 53, 5: 189, 6: 29})

In [10]:
[arr for arr in res['classes']]

[array([2, 0, 0, 0, 2, 5, 0, 0, 2, 0, 5, 5]),
 array([5, 0, 0, 0, 4, 0, 4, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 array([0, 6, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0]),
 array([0, 0, 4, 0, 5, 0, 0, 0, 0, 0, 4, 4]),
 array([0, 0, 2, 2, 0, 0, 4, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 5, 0, 2, 0, 6]),
 array([0, 0, 4, 0, 0, 5, 4, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 5, 0]),
 array([0, 0, 3, 1, 0, 0, 0, 0, 0, 5, 0, 0]),
 array([1, 0, 0, 0, 0, 6, 0, 2, 1, 0, 0, 0]),
 array([2, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 0]),
 array([0, 0, 0, 0, 5, 0, 5, 2, 0, 0, 1, 0]),
 array([0, 0, 0, 0, 5, 0, 2, 1, 0, 2, 2, 0]),
 array([0, 0, 4, 0, 0, 0, 0, 0, 0, 4, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 0]),
 array([0, 0, 0, 6, 0, 0, 0, 0, 0, 5, 0, 0]),
 array([0, 1, 0, 0, 2, 3, 0, 0, 0,

In [11]:
Counter([item for sublist in res['classes'] for item in sublist])

Counter({0: 1045, 1: 129, 2: 148, 3: 11, 4: 60, 5: 89, 6: 18})

## REPARTITION

In [3]:
from vgg_pretrained import vgg_preloaded, MelaData, train

In [4]:
import os
import torch
import pandas as pd
from skimage import io, transform
import numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader
import torch.nn as nn
from torchvision import models, transforms, utils
from PIL import Image
from tqdm import tqdm
from torch.optim import Adam
import pickle
import math

In [14]:
data_d = '/home/paperspace/projects/skin_cancer/data/skin-cancer-mnist-ham10000/HAM10000_images_part_1/'
label_dir = '/home/paperspace/projects/skin_cancer/data/skin-cancer-mnist-ham10000/HAM10000_metadata.csv'
save_dir = '/home/paperspace/projects/skin_cancer/data/res_model/'
epoch = 2
mb = 24
num_class = 7
num_workers = 1
cuda = True
conti = False
save = True
name = 'test_model'
lr = 1e-3
stage = 'transfer'

In [8]:
loss_train, acc_train, val_data = train(data_dir = data_d, label_dir = label_dir, save_dir = save_dir, epoch = epoch, mb = mb, num_class = num_class, num_workers = num_workers, use_cuda = cuda, conti = conti, lr = lr, save = True)




[Epoch 1]:  87%|████████▋ | 256/293 [02:09<00:18,  1.97it/s]


[Epoch 1]: 100%|██████████| 293/293 [02:28<00:00,  1.97it/s]

[Epoch 2]:   0%|          | 0/293 [00:00<?, ?it/s]

Train - Loss: 1.1119 Acc: 0.6646



[Epoch 2]:  88%|████████▊ | 257/293 [02:11<00:18,  1.95it/s]


[Epoch 2]: 100%|██████████| 293/293 [02:30<00:00,  1.95it/s]


Train - Loss: 1.6332 Acc: 0.6678


In [22]:
modelpath = os.path.join(save_dir, '{}.pt'.format('model'))

In [23]:
model = vgg_preloaded(7, use_cuda=cuda)
model = model.load_state_dict(torch.load(modelpath))

In [24]:
model

In [27]:
class vgg_preloaded(nn.Module):

    def __init__(self, num_class, use_cuda):
        super(vgg_preloaded, self).__init__()
        self.use_cuda = use_cuda
        self.num_class = num_class
        self.dtype = torch.cuda.FloatTensor if self.use_cuda else torch.FloatTensor
        model = models.vgg16(pretrained=True)
        self.model = model.cuda() if self.use_cuda else model
        self.model.classifier.require_grad = True
        self.model.features.require_grad = True
        

    def forward(self, inp):
        return(self.model(inp))

In [28]:
loss_train, acc_train, val_data = train(data_dir = data_d, label_dir = label_dir, save_dir = save_dir, epoch = epoch, mb = mb, num_class = num_class, num_workers = num_workers, use_cuda = cuda, conti = conti, lr = lr, save = True)


[Epoch 1]:  87%|████████▋ | 256/293 [02:09<00:18,  1.97it/s]


[Epoch 1]: 100%|██████████| 293/293 [02:28<00:00,  1.98it/s]

[Epoch 2]:   0%|          | 0/293 [00:00<?, ?it/s]

Train - Loss: 1.3366 Acc: 0.6569



[Epoch 2]:   3%|▎         | 10/293 [00:05<02:27,  1.91it/s]Process Process-5:
Traceback (most recent call last):
  File "/home/paperspace/anaconda3/envs/fastai/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/paperspace/anaconda3/envs/fastai/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/paperspace/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/paperspace/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/paperspace/anaconda3/envs/fastai/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 103, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/paperspace/projects/skin_can

KeyboardInterrupt: 