In [1]:
import pandas as pd

data_path = '../data/skin-cancer-mnist-ham10000/'

In [6]:
pd_meta = pd.read_csv(data_path + 'HAM10000_metadata.csv')

In [8]:
set(pd_meta.dx_type)

{'confocal', 'consensus', 'follow_up', 'histo'}

According to data description, only the 'follow-up' category is confirmed and therefore can be used as positive label

In [11]:
sum(pd_meta.dx_type == 'follow_up')

3704

In [18]:
set(pd_meta.dx)

{'akiec', 'bcc', 'bkl', 'df', 'mel', 'nv', 'vasc'}

According to the data description, the above categories correpond to the following diagnoses:
- Actinic keratoses and intraepithelial carcinoma / Bowen's disease (akiec)
- basal cell carcinoma (bcc)
- benign keratosis-like lesions (solar lentigines / seborrheic keratoses and lichen-planus like keratoses, bkl)
- dermatofibroma (df)
- melanoma (mel)
- melanocytic nevi (nv) 
- vascular lesions (angiomas, angiokeratomas, pyogenic granulomas and hemorrhage, vasc)

In [20]:
pd_meta.head()

lesion_id      image_id   dx dx_type   age   sex localization
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

we have about 3.7k positive labels

In [12]:
rgb_28 = pd.read_csv(data_path+'hmnist_28_28_RGB.csv')

In [19]:
rgb_28.label

0        2
1        2
2        2
3        2
4        2
5        2
6        2
7        2
8        2
9        2
10       2
11       2
12       2
13       2
14       2
15       2
16       2
17       2
18       2
19       2
20       2
21       2
22       2
23       2
24       2
25       2
26       2
27       2
28       2
29       2
        ..
9985     0
9986     0
9987     0
9988     0
9989     0
9990     0
9991     0
9992     0
9993     0
9994     0
9995     0
9996     0
9997     0
9998     0
9999     0
10000    0
10001    0
10002    0
10003    0
10004    0
10005    0
10006    0
10007    0
10008    0
10009    0
10010    0
10011    0
10012    0
10013    0
10014    6
Name: label, Length: 10015, dtype: int64

Testing out stuff

In [1]:
import numpy as np
import torch

In [209]:
one_hot = np.zeros((1, 5), dtype = np.float32)

In [210]:
one_hot[0][3] = 1

In [211]:
one_hot = torch.from_numpy(one_hot)

In [212]:
one_hot

tensor([[0., 0., 0., 1., 0.]])

In [213]:
pseudo_output = np.array([[1,2,3], [2,3,4], [2,3,4], [3,4,5], [4,5,6]])

In [214]:
pseudo_output = torch.from_numpy(pseudo_output).float().t()

In [215]:
pseudo_output

tensor([[1., 2., 2., 3., 4.],
        [2., 3., 3., 4., 5.],
        [3., 4., 4., 5., 6.]])

In [216]:
pseudo_output.shape

torch.Size([3, 5])

In [219]:
torch.sum(one_hot*pseudo_output)

tensor(12.)

In [218]:
torch.mm(one_hot, pseudo_output.t())

tensor([[3., 4., 5.]])

In [2]:
from torchvision import models

In [39]:
model_vgg16 = models.vgg16(pretrained = True)
model_vgg19 = models.vgg19(pretrained = True)

model_vgg16.eval()
model_vgg19.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace)
    (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (17): ReLU(inplace)

In [5]:
model_vgg16.eval()

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (17): Conv2d

In [95]:
for name, module in model_vgg.features._modules.items():
    print(name, module)

0 Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
1 ReLU(inplace)
2 Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
3 ReLU(inplace)
4 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
5 Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
6 ReLU(inplace)
7 Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
8 ReLU(inplace)
9 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
10 Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
11 ReLU(inplace)
12 Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
13 ReLU(inplace)
14 Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
15 ReLU(inplace)
16 MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
17 Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
18 ReLU(inplace)
19 Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
20 ReLU

In [72]:
xx = torch.randn(1,1)
xx.requires_grad = True

In [73]:
xx

tensor([[-0.6389]], requires_grad=True)

In [74]:
yy = 4 * xx

In [75]:
zz = yy**2

In [76]:
yy_grad = []
def return_grad(grad):
    yy_grad.append(grad)
yy.register_hook(return_grad)

In [77]:
zz.backward()

In [78]:
xx.grad

tensor([[-20.4462]])

In [80]:
yy_grad

[tensor([[-5.1116]])]

In [6]:
import torch
from torch.autograd import Variable
from torch.autograd import Function
from torchvision import models
from torchvision import utils
import cv2
import sys
import numpy as np
import argparse

In [8]:
from torch.autograd import Function

In [40]:
def preprocess_image(img):
	means=[0.485, 0.456, 0.406]
	stds=[0.229, 0.224, 0.225]

	preprocessed_img = img.copy()[: , :, ::-1]
	for i in range(3):
		preprocessed_img[:, :, i] = preprocessed_img[:, :, i] - means[i]
		preprocessed_img[:, :, i] = preprocessed_img[:, :, i] / stds[i]
	preprocessed_img = \
		np.ascontiguousarray(np.transpose(preprocessed_img, (2, 0, 1)))
	preprocessed_img = torch.from_numpy(preprocessed_img)
	preprocessed_img.unsqueeze_(0)
	#input = Variable(preprocessed_img, requires_grad = True)
	input = preprocessed_img
	input.requires_grad = True
	return(input)

In [41]:
class ExtractFeatures:
	"""
	Class for mannually passing the input image through the model
	the gradient at the identified layer will be registered and saved
	"""
	def __init__(self, model, target_layer):
		self.model = model
		self.target_layer = target_layer
		self.gradients = []

	def save_grad(self, grad):
		self.gradients.append(grad)

	def record_and_feed_forward(self, inp):
		# we want to reset the gradient every time we call the method
		self.gradients = []
		for name, layer in self.model.features._modules.items():
			# here we mannually pass the input through the NN until the identified layer
			inp = layer(inp)
			if name == self.target_layer:
				# here by registering the hook, we tag the layer and notify torch that we want to keep the gradient for this layer
				inp.register_hook(self.save_grad)
				# record the output at the identified layer, the output is the same as the input for the next layer (activation: final ReLU for VGG before classif)
				layer_output = inp
		# need to flatten before the fully connected layers in the classifier half
		inp = inp.view(inp.size(0), -1)
		# classify
		inp = self.model.classifier(inp)
		return(layer_output, inp)

In [77]:
target_layers = ['29']
feature_extractor = ExtractFeatures(model_vgg16.features, target_layers)

In [78]:
image_path = '/home/paperspace/projects/skin_cancer/data/skin-cancer-mnist-ham10000/HAM10000_images_part_1/ISIC_0025713.jpg'
img = cv2.imread(image_path, 1)
img = np.float32(cv2.resize(img, (224, 224))) / 255

In [79]:
inp = preprocess_image(img)

In [80]:
inp = inp.cuda()

In [81]:
model_vgg16 = model_vgg16.cuda()

In [195]:
act, output = feature_extractor(inp)

In [151]:
model_vgg16.features

Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU(inplace)
  (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): ReLU(inplace)
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (6): ReLU(inplace)
  (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): ReLU(inplace)
  (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): ReLU(inplace)
  (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (13): ReLU(inplace)
  (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (15): ReLU(inplace)
  (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (17): Conv2d(256, 512, kernel_size=(3, 3), stride=(1, 1), padding=(

In [152]:
model_vgg19.features

Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (1): ReLU(inplace)
  (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): ReLU(inplace)
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (6): ReLU(inplace)
  (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (8): ReLU(inplace)
  (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (11): ReLU(inplace)
  (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (13): ReLU(inplace)
  (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (15): ReLU(inplace)
  (16): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (17): ReLU(inplace)
  (18): MaxPool2d(kernel_size=2, stride=2, padding=0, 

In [201]:
output.size()

torch.Size([1, 512, 7, 7])

In [203]:
output.view(output.size(0),-1).size()

torch.Size([1, 25088])

In [206]:
a = 1

In [207]:
print('hi') if a is None else print('lol')

lol


In [229]:
act[-1].cpu().data.numpy()[0].shape

(512, 14, 14)

In [230]:
act[-1].cpu().data.numpy()[0, :].shape

(512, 14, 14)

In [82]:
img = inp

In [83]:
extractfeatures = ExtractFeatures(model_vgg16, '29')

In [84]:
feature, output = extractfeatures.record_and_feed_forward(img)

In [85]:
class_code = np.argmax(output.cpu().data.numpy())

In [86]:
one_hot = np.zeros((1, output.size()[-1]), dtype = np.float32)
one_hot[0][class_code] = 1
one_hot = torch.from_numpy(one_hot)
one_hot.requires_grad = True
one_hot = one_hot.cuda()

In [87]:
activation_value = torch.sum(torch.mm(one_hot, output.t()))

In [88]:
output[0].shape

torch.Size([1000])

In [89]:
activation_value = output[0][class_code]

In [90]:
activation_value

tensor(15.6454, device='cuda:0', grad_fn=<SelectBackward>)

In [91]:
model_vgg16.features.zero_grad()
model_vgg16.classifier.zero_grad()

In [92]:
activation_value.backward()

In [93]:
grads = extractfeatures.gradients[-1].cpu().data.numpy()

In [94]:
grads.shape

(1, 512, 14, 14)

In [95]:
grads = np.mean(grads, axis = (2,3))[0]

In [96]:
target_layer = feature.cpu().data.numpy()[0] # in case the input target_layer is multiple

In [115]:
cam = np.zeros(target_layer.shape[1 : ], dtype = np.float32)

In [116]:
for i, w in enumerate(grads):
    cam += w * target_layer[i, :, :]
cam = np.maximum(cam, 0)
cam = cv2.resize(cam, (600, 450))
cam = cam - np.min(cam)
cam = cam / np.max(cam)

In [117]:
image_path = '/home/paperspace/projects/skin_cancer/data/skin-cancer-mnist-ham10000/HAM10000_images_part_1/ISIC_0025713.jpg'
img = cv2.imread(image_path, 1)
#img = np.float32(cv2.resize(img, (224, 224))) / 255
img = np.float32(img) / 255

In [118]:
img.shape

(450, 600, 3)

In [119]:
heatmap = cv2.applyColorMap(np.uint8(255*cam), cv2.COLORMAP_JET)
heatmap = np.float32(heatmap) / 255
cam_ = heatmap + np.float32(img)
cam_ = cam_ / np.max(cam_)

In [ ]:
cv2.imshow('img', cam_)

In [120]:
cv2.imwrite("cam.jpg", np.uint8(255 * cam_))

True

In [103]:
np.uint8(255*cam)

array([[189, 189, 189, ...,  89,  89,  89],
       [189, 189, 189, ...,  89,  89,  89],
       [189, 189, 189, ...,  89,  89,  89],
       ..., 
       [226, 226, 226, ..., 255, 255, 255],
       [226, 226, 226, ..., 255, 255, 255],
       [226, 226, 226, ..., 255, 255, 255]], dtype=uint8)